spring.application.name=service-registry

# Eureka instance
eureka.instance.hostname=localhost

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Port for Eureka server
server.port=8761
