spring.application.name=AI-SERVICE
server.port = 8086
spring.ai.openai.api-key=${GROQAPIKEY}

spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost

eureka.instance.prefer-ip-address=true

#eureka.instance.ip-address=127.0.0.1