server.port=8082

spring.application.name=USERSERVICE

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=${PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Actuator
management.endpoints.web.exposure.include=*

file.upload-dir=uploads/resumes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.root=INFO

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
