spring.application.name= interview-service

server.port = 8085

# PostgresSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_experience
spring.datasource.username=postgres
spring.datasource.password=${PASSWORD}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL auto (update / validate / create / create-drop)
spring.jpa.hibernate.ddl-auto=update

# PostgresSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# eureka client config

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
